name: CI to GHCR and deploy to heroku

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    branches: [ "*" ]

# Set environment variables
env:
  app_name: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone git repo
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build docker image, push to registries
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/production/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Heroku registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
      -
        name: Release to heroku
        run: |
          heroku container:push web --app ${{ env.app_name }} --arg REPOID=${{ github.repository }} --recursive --context-path .
          heroku container:release web --app ${{ env.app_name }}
